# Site settings
title: "always an underachiever"
logo:
email: nhpatt@gmail.com
description: Javier Gamarra aka nhpatt
url: "http://nhpatt.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: nhpatt
github_username:  nhpatt

permalink: pretty
paginate: 5

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
